version: "3.8"

services:
  openpollution-backend:
    build:
      context: ./backend
      dockerfile: cmd/backend/Dockerfile
    depends_on:
      - ipfs
    ports:
      - "9000:9000"
    restart: always
    environment:
      ADDRESS: 0.0.0.0:9000
      PDCL_HOST: 35.216.150.202
      PDCL_PORT: 8000
      IPFS_HOST: ipfs
      IPFS_PORT: 5001
  openpollution-ui:
    build:
      context: ./ui
    ports:
      - "3000:80"
    restart: always
  ipfs:
    image: ipfs/go-ipfs:v0.11.0
    environment:
      - IPFS_PROFILE=server
      - IPFS_PATH=/ipfsdata
    volumes:
      - ./data:/ipfsdata
    ports:
      - "4001:4001" # ipfs swarm host
      - "127.0.0.1:8080:8080" # local gateway
      - "127.0.0.1:5001:5001" # api server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/v0/id"]
      interval: 30s
      timeout: 10s
      retries: 5
