env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - airbnb
  - prettier
  - plugin:import/typescript
  - plugin:jest/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - prettier
rules: 
  no-use-before-define: off
  import/extensions: off
  react/jsx-filename-extension: [1, {extensions: [".js", ".jsx", ".ts", ".tsx"]}]

